<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="System" Id="{d7288777-637e-42ff-af45-8ccee0e2f8c6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM System
VAR
	ElectricBoard: ElectricBoard;
	ConveyorEntry: ConveyorEntry;
	TransferConveyor: TransferConveyor;
	TransferToLeftorRight: TransferToLeftorRight;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//System functions.
ElectricBoard();
ConveyorEntry();
TransferConveyor();
TransferToLeftorRight();
]]></ST>
    </Implementation>
    <LineIds Name="System">
      <LineId Id="55" Count="0" />
      <LineId Id="29" Count="0" />
      <LineId Id="31" Count="0" />
      <LineId Id="38" Count="0" />
      <LineId Id="45" Count="0" />
      <LineId Id="47" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>